### ISSUE TITLE
Some annotations don't render well

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub3#31]
In particular source and target organism don't display well and data source and wasGeneratedby don't display at all. Examples of the use of these three can be found here: https://synbiohub.org/user/JMante/CIDAR_toolkit_KWK/CIDAR_toolkit_KWK_collection/1/a330d6f09b2bf4040d6012c515489e6e2674f626/share

**Comment by danielfang97** [comment]
closing this as this just has to do with the ontology issue
