### ISSUE TITLE
Admin Page: SBOLExplorer

### ISSUE THREAD

**Issue by benjhatch** [SynBioHub/synbiohub3#336]
Need to create /admin/explorer interface for admins on SynBioHub2.

**Comment by danielfang97** [comment]
Currently a copy of the status page

**Comment by cl117** [comment]
SynBioHub1 
7777/admin/SBExplore looks the same the org
SynBioHub2
3333/admin/SBExplore

**Comment by cl117** [comment]
`http://localhost:7777/admin/explorer` Admin (SBOLExplorer off: not exit, show SBOLExplorer page without an SBOLExplorer URL; SBOLExplorer on: ![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/6b54673c-23b1-40a2-bd30-971f2616b77f))
`http://localhost:3333/admin/explorer` Admin (SBOLExplorer off: not exit, the admin/status instead; SBOLExplorer on: not exit, the admin/status instead)
`https://synbiohub.org/admin/explorer` Username: my Gmail
