### ISSUE TITLE
Ensure theme color scheme is used correctly

### ISSUE THREAD

**Issue by benjhatch** [SynBioHub/synbiohub3#337]
Need to create /admin/theme interface in SynBioHub2. This doesn't really modify the core functionality of SynBioHub (it's essentially just for cosmetic purposes), so this is a lower priority (imo)

**Comment by cjmyers** [comment]
Page exists, but cannot edit

**Comment by danielfang97** [comment]
So far, can change instance name and front page text. Logo will probably be pushed to later. Color needs to be discussed.

**Comment by danielfang97** [comment]
Mostly done. Can change theme color on most areas (still need to change search navbar), and can change instance name and front page text. Icons and the checkboxes haven't been done yet.

**Comment by danielfang97** [comment]
Changed theme color with search navbar and left metadata on viewing pages

**Comment by cjmyers** [comment]
Done
