### ISSUE TITLE
OtherProperties Ability in Custom JSON

### ISSUE THREAD

**Issue by benjhatch** [SynBioHub/synbiohub3#348]
Need way to efficiently define other properties table for each of the viewing interfaces

**Comment by danielfang97** [comment]
Exclude those terms in getMetadata and getDetails

**Comment by cjmyers** [comment]
select ?p ?o 
where {
  <https://synbiohub.org/public/igem/BBa_F2620/1>
  ?p 
  ?o
  Filter(!strstarts(str(?p),'http://sbols.org/') && !strstarts(str(?p),'http://www.w3.org/ns/prov#') && 
        ?p != <http://purl.org/dc/terms/title> && ?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
  }

**Comment by danielfang97** [comment]
closed with #554
