### ISSUE TITLE
Error messages on problems communicating with the backend

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#362]
Rather than a promise rejection, should determine the incorrect response information from backend and display the HTTP code with any error message in a popup window.

**Comment by danielfang97** [comment]
Mostly works, but is not very clean. Also, doesn't handle 500 errors. Only 400 errors.

**Comment by cjmyers** [comment]
Often happens when auto-logged out, should check for this and give a clear message how to fix

**Comment by danielfang97** [comment]
Make a mini error box. Look at errors.js

**Comment by danielfang97** [comment]
Completed with #616
