### ISSUE TITLE
Frontend should remove invalid user sessions

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#412]
If a request using the current token fails, this means the token is invalid and the user session should be deleted.

**Comment by cjmyers** [comment]
401 HTTP code received indicates invalid token

**Comment by danielfang97** [comment]
A common error that occurs is "cannot access other users' graphs". Instead of just displaying this error, it should:
1. log user out on SBH2 visually (is logged out, but display not updated to reflect that)
2. send user to login page

**Comment by danielfang97** [comment]
Fixed with PR #576
