### ISSUE TITLE
Schema.org markup on home page

### ISSUE THREAD

**Issue by kcmcleod** [SynBioHub/synbiohub3#46]
In addition to https://github.com/SynBioHub/synbiohub/issues/986

There are issues with:
1. the provider is listed as foo@example.com:
```
  "provider": [
    "foo@example.com"
  ],
```

2. the DataCatalog description has html tags in it:
```
"<a href=\"/About\">SynBioHub</a> is a <i>design repository</i> for ...
```

**Comment by danielfang97** [comment]
fixed now
