### ISSUE TITLE
the Plan and Datasheet JSON metadata section takes up too much space

### ISSUE THREAD

**Issue by qwest123987** [SynBioHub/synbiohub3#490]
Could potentially be an issue with JSON pages that don't have a type starting with: http://sbols.org

**Comment by cjmyers** [comment]
Trim the type to the last delimiter "#", "/", "%"

**Comment by cjmyers** [comment]
The URL linked should not be to SBOL2 ontology unless it is SBOL2, otherwise just link to the URI

**Comment by cjmyers** [comment]
Redirect to dissy is unnecessary, simply make the URL be the URI for the type of the object
