### ISSUE TITLE
Sequence JSON needs to display the sequence in a more readable format

### ISSUE THREAD

**Issue by qwest123987** [SynBioHub/synbiohub3#491]
The current JSON displays a sequence that is just an unreadably long string

**Comment by danielfang97** [comment]
@cjmyers Is this an actual issue? Do we want to change the way sequences are displayed? (just a long ATCG string)

**Comment by cjmyers** [comment]
Yes, see SBH1 for how to display better

**Comment by danielfang97** [comment]
Closing for now, refer to #521
