### ISSUE TITLE
If a link doesn't exist sometimes the displayId cannot be retrieved

### ISSUE THREAD

**Issue by qwest123987** [SynBioHub/synbiohub3#493]
For example, in the CombinatorialDerivation JSON the template metadata first travels to the given url then gets the displayId for the template, but if the url is invalid the displayId cannot be fetched, so it will instead remain a link

**Comment by cjmyers** [comment]
If displayId cannot be fetched, should derive one from the URI.  For SBOL2 objects, the id should be the value between the last and second to last delimiter ("/", "%", "#").  If not SBOL2 object, it should simply be the value after the last delimiter.

**Comment by danielfang97** [comment]
Closed for now. Should be fixed with issue #522
