### ISSUE TITLE
Jsonpages current progress

### ISSUE THREAD

**Issue by danielfang97** [SynBioHub/synbiohub3#497]
JSON Pages (SBOL 2)

- [ ] ModuleInstance does not exist? (George)
- [ ] VariableComponent does not exist? George)
- [ ] The rest of the provenance ones (activity)
- [ ] potentially do ontology of major ones as well
- [ ] GenericTopLevel
- [x] TopLevel / Datasheet(George)
- [x] Plan (George)
- [x] SequenceAnnotation (Daniel)
- [x] Location (Daniel)
- [x] SequenceConstraint (George)
- [x] Module (George)
- [x] Participation (George)
- [x] Interaction (George)
- [x] ModuleDefinition (George)
- [x] Component
- [x] FunctionalComponent
- [x] MapsTo
- [x] CombinatorialDerivation (George)
- [x] Collection
- [x] Attachment
- [x] ExperimentalData
- [x] Implementation
- [x] ComponentInstance (is this one actually done?)
- [x] ComponentDefinition (George)
- [x] Model
- [x] Experiment (George)

**Comment by cjmyers** [comment]
Done but needs testing
