### ISSUE TITLE
Remove all synbiohub.org in the code

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#520]
There should be no assumptions that synbiohub.org is the URL of the instance

**Comment by danielfang97** [comment]
Should be mostly all cleaned up. Would need to resort to testing to ensure further

**Comment by danielfang97** [comment]
Found these instances of using synbiohub.org. Need to clean these up

basketitem.js
standardsearch.js
resultrow.js
Submissiondisplay.js
submissionstatuspanel.js
sidepanel.js
Members.js
Attachmentrows.js
uploadattachment.js
getQueryResponse.js

**Comment by danielfang97** [comment]
Get registries. Check if one of the urls in the registries is localhost. If so, then this means instanceURL is the one associated with this registry entry. And replace all the synbiohub.org with this value. If link however, replace with "/"

**Comment by danielfang97** [comment]
May still want to expose databasePrefix and instanceURL through theme in SBH1. Maybe even triplestore to get things like default graph URI?

**Comment by danielfang97** [comment]
[] basketitem.js
[] standardsearch.js
[] resultrow.js
[] Submissiondisplay.js
[] submissionstatuspanel.js
[] sidepanel.js
[] Members.js
[] Attachmentrows.js
[] uploadattachment.js
[] getQueryResponse.js

**Comment by danielfang97** [comment]
Everything except for the two above have been done. Those 2 are a little special in that they need links to the config.

**Comment by danielfang97** [comment]
Just checked and all the instances of synbiohub.org are gone
