### ISSUE TITLE
Sequence Json pages not working

### ISSUE THREAD

**Issue by danielfang97** [SynBioHub/synbiohub3#521]
Sequences never load. Something wrong with the query to get the sequence.

**Comment by cjmyers** [comment]
Format the sequence in a easy to read form, namely:

0001 tccctatcag tgatagagat tgacatccct atcagtgata gagatactga
0051 gcactactag agaaagagga gaaatactag atgaaaaaca taaatgccga
0101 cgacacatac agaataatta ataaaattaa agcttgtaga agcaataatg

**Comment by cjmyers** [comment]
Make sure to use a fixed width font
