### ISSUE TITLE
Make the add new filters replace the previous dropdown box

### ISSUE THREAD

**Issue by cl117** [SynBioHub/synbiohub3#557]
- [x] When the user selects the dropdown list of one box, it replaces it with the next dropdown box.
- [x] Change the first dropdown into a title, keep predicate (verb) and object.
- [x] Current behavior from Dev2, after click search button, the extra filters box left, depends on how many extra filter used before
- [x] Make the extra filters remember the previous selection
- [x] Support multiple filters
- [x] move the cross beside

**Comment by cl117** [comment]
AdditonalFileter.js receive properties wrong, with only the first filter -> check the options.js
console.log("index", properties.index);
console.log("filter current: ", properties.extraFilters[properties.index].filter);
output from options.js
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/67b4c55a-44fd-441e-be7d-7d6740b516e8)
after click search
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/ec056b42-0f66-4c90-bcdb-65a3d2358031)
search with 3 subjects 
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/8ba9d157-3b1f-49fd-b747-cb733d2b8598)
After search with 1 filter
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/805914b5-1dc6-4748-a4f0-7839ec07339a)

**Comment by cl117** [comment]
After click search butter, doesn't keep the other extra filters except the first one. 
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/b6ac9d45-6d6b-40c6-a216-3efbb8c7176e)

**Comment by cl117** [comment]
WHERE {
       ?subject dcterms:created ?cdate .    ?subject dcterms:modified ?mdate .    ?subject rdf:type <http://sbols.org/v2#ComponentDefinition> .    ?subject dcterms:created <2003-01-31T12:00:00Z> .    ?subject dcterms:modified <2015-08-31T04:07:20Z> . 
extraFilters
: 
Array(3)
0
{filter: 'rdf:type', value: 'http://sbols.org/v2#ComponentDefinition', id: 0}
1
{filter: 'dcterms:created', value: '2003-01-31T12:00:00Z', id: 1}
2
{filter: 'dcterms:modified', value: '2015-08-31T04:07:20Z', id: 2}
length
3

**Comment by cjmyers** [comment]
Predicate X should delete the entire filter

**Comment by cl117** [comment]
> Predicate X should delete the entire filter

That X is for clear in the `WindowedSelect`, can't add onClick function to it.

**Comment by cl117** [comment]
🐛 when not click "search" -> add 2 filters -> delete the first filter -> the value of selection replace the 2nd value -> when click search -> become correct
![image](https://github.com/SynBioHub/synbiohub3/assets/13355576/3f87db6a-99e1-49bb-ad05-c9050ac357f0)
