### ISSUE TITLE
manage submissions crashes to white screen

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#561]
Console error is here:

      var te = [{
                value: "name",
                label: "Name"
            }, {
                value: "displayId",
                label: "Display ID"
            }, {
                value: "type",
                label: "Type"
            }, {
                value: "privacy",
                label: "Privacy"
            }],
            ne = function(e, t) {
                return e.toLowerCase() > t.toLowerCase() ? 1 : -1
            },

**Comment by danielfang97** [comment]
const compareStrings = (string1, string2) => {
  if (string1 && string2) {
    return (string1.toLowerCase() > string2.toLowerCase() && 1) || -1;
  }
  return -1;
  
};

Line 132 submissions.js
