### ISSUE TITLE
When backend goes down, should given an error that it cannot communicate with the backend

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#590]

**Comment by danielfang97** [comment]
Request failed for GET /admin/registries
http://localhost:7777/admin/registries
Error Information:
Name
Error

Message
Network Error

Response Data
Stack
Error: Network Error at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15) at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:99:14)

**Comment by danielfang97** [comment]
Completed with #616
