### ISSUE TITLE
Non-compatible plugins showing on object pages

### ISSUE THREAD

**Issue by ykho001** [SynBioHub/synbiohub3#629]
In every Component in [dev.synbiohub.org](http://dev.synbiohub.org/) seen so far, the iGEM page plugins show up, unnecessarily occupying page space. Here is an example for a Component in the SEGA collection (https://dev.synbiohub.org/public/SEGA/SEGA030/1).

![image](https://github.com/SynBioHub/synbiohub3/assets/51926699/930c1a1a-dcf7-4ffa-b360-deeb37e8256f)

Proposal 1: It would be useful to have a way of setting which plugins will show up, either at an instance management level or as users submitting a collection. 

This issue is present also in [synbiohub.org](http://synbiohub.org/) and [dev2.synbiohub.org](http://dev2.synbiohub.org/)
Whilst possible to “hide” these plugins (green box) in dev2 at the user level, the boxes (blue outline) remain on the page, again occupying page space (e.g. https://dev2.synbiohub.org/public/SEGA/SEGA030/1).

![image](https://github.com/SynBioHub/synbiohub3/assets/51926699/fdca6b7f-e650-48d0-b784-78793b146352)

Proposal 2: per Proposal 1, to remove the hidden plugins from the navigation panel and page body, as well as provide a drop-down box option at the bottom (or top) of the “Page Sections” on the navigation panel to allow users to select/show plugins that have been hidden.

**Comment by fxbuson** [comment]
There is a third option too. Chris mentioned the plugins shouldn't be showing up in the first place, so this might be an actual issue instead of a new feature proposal. I don't know if there is already auto plugin-compatibility detection, but it's surely not working if it exists.

Either way, I think having the ability to hide/show plugins at the instance or collection upload level is a better solution.

**Comment by cjmyers** [comment]
Need to ensure that plugin tables are removed either when not appropriate or fail.

**Comment by cjmyers** [comment]
@zane-perry Is this fixed now?

**Comment by ykho001** [comment]
Hi, not sure if these fixes are a still a WIP, but we can't see the Accurat plugins (Accurat VisBol, Accurat SeqViz, Accurat Component Use) anymore? 
This is on [synbiohub.org](http://synbiohub.org/) and [dev2.synbiohub.org](http://dev2.synbiohub.org/). 
Going to [dev.synbiohub.org](http://dev.synbiohub.org/) leads to "502 Bad Gateway" error - is this no longer being used?

**Comment by cjmyers** [comment]
We have taken dev down, likely permanently.  The Accurat plugins were setup on Dev.  We need to move the setup to synbiohub.org.  Can you remind us where they are hosted and we can set them back up?

**Comment by ykho001** [comment]
Ah good to know! We're looking to transition the plugins from the Accurat server to our server. Will aim to provide you details on this by the end of next week, thanks!

**Comment by cjmyers** [comment]
We believe this is working now
