### ISSUE TITLE
Crashes when there is a problem with a collection name

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#644]
When there is a collection that has a name issue (t.name.includes), the entire front-end crashes with null exception.

**Comment by danielfang97** [comment]
Closed with #658. 
@cjmyers check to see if this is fixed

**Comment by cjmyers** [comment]
Still problem:

TypeError: null is not an object (evaluating 'e.toLowerCase')
ne — submissions-070659d98bfd37e23cf6.js:1:21535
sort
(anonymous function) — 5310f49360a2a07e8d5e96e333c27f1fc54ef7c3.96d7b657624a669c5557.js:1:488978
Oi — framework.692027545bc809cf9b5b.js:1:117733
(anonymous function) — framework.692027545bc809cf9b5b.js:1:3877
(anonymous function) — framework.692027545bc809cf9b5b.js:1:117106
F — framework.692027545bc809cf9b5b.js:1:2936
(anonymous function) — framework.692027545bc809cf9b5b.js:1:1658

**Comment by cjmyers** [comment]
Different one though

**Comment by danielfang97** [comment]
@cjmyers Is this happening in the root collections page?

**Comment by cjmyers** [comment]
It happens when I try to view my collections

**Comment by danielfang97** [comment]
Fixed with #672
