### ISSUE TITLE
When login is required should go to login page when trying to view collections, search, etc.

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#688]
If login is required for all operations, should take you to login screen if you try to do anything other than login.

**Comment by danielfang97** [comment]
Root collections and search lead to errors instead of redirecting to login page

**Comment by danielfang97** [comment]
Working correctly now, but is contingent on PR for fixThemeUpdate on SBH1

**Comment by danielfang97** [comment]
Closed with #821
