### ISSUE TITLE
Expose more information currently hidden in concertinas

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioHub/synbiohub3#7]
In the current SynBioHub interface, lots of information is hidden in concertina elements that are initially closed, which requires lots of clicking to expose information.

In SynBioHub3 it would be good to make as much information initially visible as possible, and to instead save space by making the table designs compact (and perhaps truncating after a few rows until a user clicks to expand them).

**Comment by danielfang97** [comment]
not planning on changing SBH2 interface design atm. can be seen @ dev2.synbiohub.org
kinda feel like the desisn interface really does help with this
