### ISSUE TITLE
Custom filters not working for custom namespaces

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#704]
Cannot filter by igem/cello/etc. properties

**Comment by cjmyers** [comment]
I was unable to filter with advanced search on dev2 these custom annotation fields for some reason

**Comment by cl117** [comment]
![image](https://github.com/user-attachments/assets/c76cec31-700f-4895-943b-46d8e4afbc9d)
Additional search -> select igem:status -> error

**Comment by cjmyers** [comment]
Should try both logged in and out

Should add and remove filters

Should investigate the query sent when it showing that there are no results to make sure query is correct

**Comment by cl117** [comment]
WHERE {
           ?subject igem:status <http://wiki.synbiohub.org/wiki/Terms/igem#status/Planning> . FILTER ((CONTAINS(lcase(?displayId), lcase('gfp'))||CONTAINS(lcase(?name), lcase('gfp'))||CONTAINS(lcase(?description), lcase('gfp'))))

        ?subject a ?type .
        ?subject sbh:topLevel ?subject .

**Comment by cl117** [comment]
I tried both login and logout. No errors.

**Comment by cl117** [comment]
info: query:igem:status=<http://wiki.synbiohub.org/wiki/Terms/igem#status/Deleted>&gfp
info: template:  {"criteria":["   ?subject igem:status <http://wiki.synbiohub.org/wiki/Terms/igem#status/Deleted> . FILTER ((CONTAINS(lcase(?displayId), lcase('gfp'))||CONTAINS(lcase(?name), lcase('gfp'))||CONTAINS(lcase(?description), lcase('gfp'))))"],"offset":"","limit":" LIMIT 50","from":""}

**Comment by cjmyers** [comment]
Cannot reproduce
