### ISSUE TITLE
Setup needs to guess https URL and URI prefixes correctly

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#778]
Right now, it is guessing these as http, it needs to guess it as https, if it is running as a secure web server

This setup fix should also be done for SynBioHub 1

**Comment by cjmyers** [comment]
Looks like can use req.secure to know if it is https.  Need to do this for by SBH1 and SBH3

**Comment by cjmyers** [comment]
Fixed by PR #1580 for SBH1.  Still needs fix for SBH2 setup.

**Comment by cjmyers** [comment]
Not working on SBH1

**Comment by cjmyers** [comment]
Another PR created for SBH1 to hopefully fix this issue

**Comment by cjmyers** [comment]
SBH2 is guessing https correctly.  However, it is not guessing the backend URL correctly.  However, it is not clear how it can guess that.  Backend URL cannot be easily guessed, so it must be a required option not an advanced option.  It should have instructions that indicate that it should be http://localhost:7777 when testing locally, but it should be the URL of the SBH1 backend otherwise.

**Comment by danielfang97** [comment]
Closed with #818
